services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: http://localhost:6014
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://docmost:NWYK82jbqqRrXMud@db:5432/docmost?schema=public
      REDIS_URL: redis://redis:6379
      MAIL_DRIVER: smtp
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: 587
      SMTP_USERNAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PW}
      SMTP_SECURE: false
      MAIL_FROM_ADDRESS: ${SMTP_FROM}
      MAIL_FROM_NAME: Docmost
    networks:
      - docmost
    ports:
      - 6014:3000
    restart: unless-stopped
    volumes:
      - ./docmost:/app/data/storage
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: NWYK82jbqqRrXMud
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - ./db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - ./redis_data:/data
networks:
  docmost:
    external: true
