services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - SETTINGS_ENCRYPTION_KEY=${KEY}
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=${WEB_PW}
    volumes:
      - ./config:/config
      - /mnt/data/backups:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped
networks: {}
