services:
  crawl4ai:
    networks:
      - crawl4ai
    ports:
      - 11235:11235
    container_name: crawl4ai
    shm_size: 1g
    image: unclecode/crawl4ai:latest
    environment:
     - CRAWL4AI_API_TOKEN=${TOKEN}
networks:
  crawl4ai:
    external: true
