services:
  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    network_mode: host
    command: tunnel --no-autoupdate run --token
      tokenhere
  cloudflare-ddns:
    restart: unless-stopped
    image: oznu/cloudflare-ddns:latest
    network_mode: host
    environment:
      - API_KEY=${DDNS_TOKEN}
      - ZONE=${DOMAIN}
      - PROXIED=${PROXIED}
  nginxproxymanager:
    restart: unless-stopped
    image: jc21/nginx-proxy-manager:2.10.4
    network_mode: host
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks: {}
